export default {
  LOAD_SOURCE_EMOJI: 'LOAD_SOURCE_EMOJI',
  LOAD_SOURCE_EMOJI_FULFILLED: 'LOAD_SOURCE_EMOJI_FULFILLED',
  LOAD_SOURCE_EMOJI_PENDING: 'LOAD_SOURCE_EMOJI_PENDING',
  LOAD_SOURCE_EMOJI_REJECTED: 'LOAD_SOURCE_EMOJI_REJECTED',
};
