export default {
  LOAD_SOURCE_EMOJI: 'LOAD_SOURCE_EMOJI',
  LOAD_SOURCE_EMOJI_FULFILLED: 'LOAD_SOURCE_EMOJI_FULFILLED',
  LOAD_SOURCE_EMOJI_PENDING: 'LOAD_SOURCE_EMOJI_PENDING',
  LOAD_SOURCE_EMOJI_REJECTED: 'LOAD_SOURCE_EMOJI_REJECTED',

  SELECT_SOURCE_EMOJI: 'SELECT_SOURCE_EMOJI',

  SET_SOURCE_EMOJI_FILTER_STRING: 'SET_SOURCE_EMOJI_FILTER_STRING',

  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',

  TRANSFER_SELECTED_EMOJI: 'TRANSFER_SELECTED_EMOJI',

  SET_API_TOKENS: 'SET_API_TOKENS',
};
